spring.application.name=OrdemServico
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/cvdo_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=cvdo
spring.datasource.password=gmSenai
spring.jpa.show-sql=True
